[build]
  command = "pnpm install && pnpm run build"
  publish = "dist"
  base = "dashboard"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 